# Generated by Django 4.1.4 on 2023-01-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachprofile",
            name="avatar",
            field=models.ImageField(
                default="media/profile_images/avatar.svg",
                upload_to="media/profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="sportsmanprofile",
            name="avatar",
            field=models.ImageField(
                default="media/profile_images/avatar.svg",
                upload_to="media/profile_images/",
            ),
        ),
    ]
