# Generated by Django 4.1.4 on 2023-01-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_coachprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportsmanprofile",
            name="club",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.club"
            ),
        ),
    ]
