# Generated by Django 4.1.4 on 2023-01-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_sportsmanprofile_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
