# Generated by Django 4.1.4 on 2023-01-19 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_workout_mark_alter_message_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
